debug: true
spring:
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      indent-output: true
blog:
  title: Blog
  banner:
    title: Warning
    content: The blog will be down tomorrow.